// ข้อความของหน้าบทเรียนที่ไม่ได้อยู่ในเนื้อหา (Lesson.texts) — เป็นข้อความสำหรับพ่อหรือข้อความระบบ
// Designer ปรับได้ที่ไฟล์นี้ที่เดียว (ไม่มีคำเรียกให้ลูกเห็นเวลา/คะแนน)
export const lessonStrings = {
  notYetOpen: 'ส่วนถัดไปของบทนี้ยังไม่เปิดให้เล่นในเวอร์ชันนี้',
  backHome: 'กลับหน้าหลัก',
  part: { check: 'เช็คก่อน', A: 'ส่วน A', B: 'ส่วน B' },
  outcome: {
    passed: 'ผ่าน',
    'passed-trend': 'ผ่าน (กำลังไปได้ดี)',
    'not-passed': 'ยังไม่ผ่าน',
    skipped: 'ข้าม',
    done: 'ทำแล้ว',
    todo: 'ยังไม่ได้ทำ',
    stalled: 'ยังไม่ผ่านซ้ำ (แจ้ง Designer)',
  } as Record<string, string>,
  flag: {
    'talk-A': 'ส่วน A: Number Talks',
    'tray-B1': 'ส่วน B: ทำ B1 ด้วยของจริง',
    'stalled-A': 'ส่วน A ยังไม่ผ่านซ้ำ',
    'stalled-B': 'ส่วน B ยังไม่ผ่าน',
  } as Record<string, string>,
  sessionSummaryTitle: 'สรุปครั้งนี้',
  flagsHeading: 'สิ่งที่พ่อต้องทำ',
  noteFor: (part: string) => `บันทึกของ${part}`,
  noteFrequency: { none: 'ไม่ใช้', some: 'บางข้อ', most: 'เกือบทุกข้อ' } as Record<string, string>,
  parentPage: {
    linkSection: 'บทเรียน',
    openLink: (title: string) => `${title} (หน้าพ่อ)`,
    back: 'กลับหน้าสำหรับพ่อ',
    progressHeading: 'ความก้าวหน้า',
    sittingsDone: (n: number) => `ทำแล้ว ${n} ครั้ง`,
    currentSitting: (n: number) => `ครั้งถัดไป: ครั้งที่ ${n}`,
    skippedByCheck: 'ข้ามส่วนที่ทำได้แล้วจากเช็คก่อน',
    metrics: (c: number, t: number) => `ถูก ${c}/${t}`,
    challengeHeading: 'คำถามต่อยอดปริศนา',
    answerLabel: 'เฉลย',
    notesHeading: 'บันทึกของพ่อ',
    noNote: 'ยังไม่มีบันทึก',
    latestNote: 'บันทึกล่าสุด',
    tableHeading: 'รายละเอียดทุกข้อ',
    timeFootnote: '* เวลาใช้ไม่ได้ (สลับแท็บระหว่างตอบ)',
    columns: {
      item: 'ข้อ',
      section: 'ส่วน',
      problem: 'โจทย์',
      response: 'คำตอบ',
      result: 'ถูก/ผิด',
      time: 'เวลา (วิ)',
      fluent: 'คล่อง',
      mind: 'ในหัวเห็นอะไร',
      misconception: 'ความเข้าใจผิด',
      step: 'ขั้นย่อย',
    },
    right: 'ถูก',
    wrong: (expected: number) => `ผิด (เฉลย ${expected})`,
    fluentYes: 'ใช่',
    fluentNo: 'ไม่',
  },
};
