import type { Diagnostic, DiagnosticItem, FlashVisual } from '@/engine/types';
import { additionLadder } from '@/content/ladders';
import { addMisconceptions } from '@/content/misconceptions';
import { addStrategySets } from '@/content/strategies';

const FLASH: FlashVisual = {
  type: 'ten-frame',
  mode: 'flash',
  readyMs: 900,
  flashMs: 1500,
  colorMode: 'single',
};

const stage1Items: DiagnosticItem[] = [
  {
    id: '1.1',
    skillId: 'add.subitize-10',
    ladderSteps: [1],
    input: 'keypad',
    problem: { kind: 'subitize', count: 7, visual: 'ten-frame' },
    expected: 7,
    visual: FLASH,
    wrongAnswers: [
      { response: 6, misconceptionId: 'M1' },
      { response: 8, misconceptionId: 'M1' },
      { response: 5, misconceptionId: 'M2' },
      { response: 3, misconceptionId: 'M3' },
    ],
  },
  {
    id: '1.2',
    skillId: 'add.subitize-10',
    ladderSteps: [1],
    input: 'keypad',
    problem: { kind: 'subitize', count: 9, visual: 'ten-frame' },
    expected: 9,
    visual: FLASH,
    wrongAnswers: [
      { response: 8, misconceptionId: 'M1' },
      { response: 10, misconceptionId: 'M1' },
      { response: 5, misconceptionId: 'M2' },
      { response: 1, misconceptionId: 'M3' },
    ],
  },
  {
    id: '1.3',
    skillId: 'add.subitize-10',
    ladderSteps: [1],
    input: 'keypad',
    problem: { kind: 'subitize', count: 6, visual: 'ten-frame' },
    expected: 6,
    visual: FLASH,
    wrongAnswers: [
      { response: 7, misconceptionId: 'M1' },
      { response: 5, misconceptionId: 'M2' },
      { response: 4, misconceptionId: 'M3' },
    ],
  },
  {
    id: '1.4',
    skillId: 'add.subitize-10',
    ladderSteps: [1],
    input: 'keypad',
    problem: { kind: 'subitize', count: 8, visual: 'ten-frame' },
    expected: 8,
    visual: FLASH,
    wrongAnswers: [
      { response: 7, misconceptionId: 'M1' },
      { response: 9, misconceptionId: 'M1' },
      { response: 5, misconceptionId: 'M2' },
      { response: 2, misconceptionId: 'M3' },
    ],
  },
];

const stage2Items: DiagnosticItem[] = [
  {
    id: '2.1',
    skillId: 'add.bonds-10',
    ladderSteps: [2],
    input: 'keypad',
    problem: { kind: 'missing-part', whole: 10, part: 7 },
    expected: 3,
    fluentMs: 3000,
    wrongAnswers: [
      { response: 2, misconceptionId: 'M5' },
      { response: 4, misconceptionId: 'M5' },
      { response: 17, misconceptionId: 'M4' },
    ],
  },
  {
    id: '2.2',
    skillId: 'add.bonds-10',
    ladderSteps: [2],
    input: 'keypad',
    problem: { kind: 'missing-part', whole: 10, part: 4 },
    expected: 6,
    fluentMs: 3000,
    wrongAnswers: [
      { response: 5, misconceptionId: 'M5' },
      { response: 7, misconceptionId: 'M5' },
      { response: 14, misconceptionId: 'M4' },
    ],
  },
  {
    id: '2.3',
    skillId: 'add.bonds-10',
    ladderSteps: [2],
    input: 'keypad',
    problem: { kind: 'missing-part', whole: 10, part: 8 },
    expected: 2,
    fluentMs: 3000,
    wrongAnswers: [
      { response: 1, misconceptionId: 'M5' },
      { response: 3, misconceptionId: 'M5' },
      { response: 18, misconceptionId: 'M4' },
    ],
  },
  {
    id: '2.4',
    skillId: 'add.bonds-10',
    ladderSteps: [2],
    input: 'keypad',
    problem: { kind: 'missing-part', whole: 10, part: 3 },
    expected: 7,
    fluentMs: 3000,
    wrongAnswers: [
      { response: 6, misconceptionId: 'M5' },
      { response: 8, misconceptionId: 'M5' },
      { response: 13, misconceptionId: 'M4' },
    ],
  },
];

const stage3Items: DiagnosticItem[] = [
  {
    id: '3.1',
    skillId: 'add.doubles',
    ladderSteps: [3],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 6, b: 6 },
    expected: 12,
    fluentMs: 3000,
    wrongAnswers: [
      { response: 11, misconceptionId: 'M5' },
      { response: 13, misconceptionId: 'M5' },
      { response: 2, misconceptionId: 'M6' },
    ],
  },
  {
    id: '3.2',
    skillId: 'add.doubles',
    ladderSteps: [3],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 8, b: 8 },
    expected: 16,
    fluentMs: 3000,
    wrongAnswers: [
      { response: 15, misconceptionId: 'M5' },
      { response: 17, misconceptionId: 'M5' },
      { response: 6, misconceptionId: 'M6' },
    ],
  },
  {
    id: '3.3',
    skillId: 'add.doubles',
    ladderSteps: [3],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 6, b: 7 },
    expected: 13,
    fluentMs: 4000,
    strategySetId: 'add.single-digit',
    wrongAnswers: [
      { response: 12, misconceptionId: 'M5', byStrategy: { doubles: 'M8' } },
      { response: 14, misconceptionId: 'M5', byStrategy: { doubles: 'M8' } },
      { response: 3, misconceptionId: 'M6' },
    ],
  },
  {
    id: '3.4',
    skillId: 'add.doubles',
    ladderSteps: [3],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 7, b: 8 },
    expected: 15,
    fluentMs: 4000,
    strategySetId: 'add.single-digit',
    wrongAnswers: [
      { response: 14, misconceptionId: 'M5', byStrategy: { doubles: 'M8' } },
      { response: 16, misconceptionId: 'M5', byStrategy: { doubles: 'M8' } },
      { response: 5, misconceptionId: 'M6' },
    ],
  },
];

const stage4Items: DiagnosticItem[] = [
  {
    id: '4.1',
    skillId: 'add.make-10',
    ladderSteps: [4],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 8, b: 5 },
    expected: 13,
    fluentMs: 4000,
    strategySetId: 'add.single-digit',
    wrongAnswers: [
      { response: 12, misconceptionId: 'M5' },
      { response: 14, misconceptionId: 'M5' },
      { response: 3, misconceptionId: 'M6' },
      { response: 15, misconceptionId: 'M7' },
      { response: 18, misconceptionId: 'M7' },
    ],
  },
  {
    id: '4.2',
    skillId: 'add.make-10',
    ladderSteps: [4],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 9, b: 6 },
    expected: 15,
    fluentMs: 4000,
    strategySetId: 'add.single-digit',
    wrongAnswers: [
      { response: 14, misconceptionId: 'M5' },
      { response: 16, misconceptionId: 'M5', byStrategy: { 'make-ten': 'M7' } },
      { response: 19, misconceptionId: 'M7' },
      { response: 5, misconceptionId: 'M6' },
    ],
  },
  {
    id: '4.3',
    skillId: 'add.make-10',
    ladderSteps: [4],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 7, b: 4 },
    expected: 11,
    fluentMs: 4000,
    strategySetId: 'add.single-digit',
    wrongAnswers: [
      { response: 10, misconceptionId: 'M5' },
      { response: 12, misconceptionId: 'M5' },
      { response: 1, misconceptionId: 'M6' },
      { response: 14, misconceptionId: 'M7' },
      { response: 17, misconceptionId: 'M7' },
    ],
  },
  {
    id: '4.4',
    skillId: 'add.make-10',
    ladderSteps: [4],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 4, b: 9 },
    expected: 13,
    fluentMs: 4000,
    strategySetId: 'add.single-digit',
    wrongAnswers: [
      { response: 12, misconceptionId: 'M5' },
      { response: 14, misconceptionId: 'M5', byStrategy: { 'make-ten': 'M7' } },
      { response: 19, misconceptionId: 'M7' },
      { response: 3, misconceptionId: 'M6' },
    ],
  },
];

const stage5Items: DiagnosticItem[] = [
  {
    id: '5.1',
    skillId: 'add.tens',
    ladderSteps: [5],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 47, b: 10 },
    expected: 57,
    fluentMs: 5000,
    wrongAnswers: [
      { response: 48, misconceptionId: 'M9' },
      { response: 56, misconceptionId: 'M5' },
      { response: 58, misconceptionId: 'M5' },
    ],
  },
  {
    id: '5.2',
    skillId: 'add.tens',
    ladderSteps: [5],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 30, b: 40 },
    expected: 70,
    fluentMs: 5000,
    wrongAnswers: [
      { response: 7, misconceptionId: 'M9' },
      { response: 69, misconceptionId: 'M5' },
      { response: 71, misconceptionId: 'M5' },
    ],
  },
  {
    id: '5.3',
    skillId: 'add.2digit',
    ladderSteps: [6, 7],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 38, b: 25 },
    expected: 63,
    fluentMs: 15000,
    strategySetId: 'add.two-digit',
    wrongAnswers: [
      { response: 53, misconceptionId: 'M10' },
      { response: 513, misconceptionId: 'M11' },
      { response: 62, misconceptionId: 'M5' },
      { response: 64, misconceptionId: 'M5' },
    ],
  },
  {
    id: '5.4',
    skillId: 'add.2digit',
    ladderSteps: [8],
    input: 'keypad',
    problem: { kind: 'arith', op: '+', a: 49, b: 26 },
    expected: 75,
    fluentMs: 15000,
    strategySetId: 'add.two-digit',
    wrongAnswers: [
      { response: 65, misconceptionId: 'M10' },
      { response: 615, misconceptionId: 'M11' },
      { response: 74, misconceptionId: 'M5', byStrategy: { round: 'M12' } },
      { response: 76, misconceptionId: 'M5', byStrategy: { round: 'M12' } },
    ],
  },
];

export const DX_ADD: Diagnostic = {
  kind: 'diagnostic',
  id: 'DX-ADD',
  version: 'DX-ADD v2',
  title: 'ภารกิจสำรวจการบวก',
  ladder: additionLadder,
  misconceptions: addMisconceptions,
  strategySets: addStrategySets,
  timing: { ackMs: 1000 },
  stages: [
    {
      id: 's1',
      number: 1,
      title: 'เห็นภาพ 10 ช่อง',
      intro: 'ด่าน 1 · เห็นภาพ 10 ช่อง — ภาพจะโผล่มาแป๊บเดียว นับไม่ทันก็ไม่เป็นไร ลองดูทั้งภาพ',
      instruction: 'ดูภาพให้ดี แล้วบอกว่ามีจุดกี่จุด',
      level: { good: { minCorrect: 4 }, mid: { minCorrect: 3 } },
      items: stage1Items,
    },
    {
      id: 's2',
      number: 2,
      title: 'คู่รวม 10',
      intro: 'ด่าน 2 · คู่รวม 10 — เติมตัวเลขให้ได้ 10',
      instruction: 'เติมตัวเลขให้ได้ 10',
      level: { good: { minCorrect: 4, minFluent: 3 }, mid: { minCorrect: 3 } },
      items: stage2Items,
    },
    {
      id: 's3',
      number: 3,
      title: 'เลขคู่',
      intro: 'ด่าน 3 · เลขคู่ — คิดในใจแล้วตอบ',
      instruction: 'คิดในใจ แล้วตอบ',
      level: { good: { minCorrect: 4, minFluent: 3, maxCounting: 0 }, mid: { minCorrect: 3 } },
      items: stage3Items,
    },
    {
      id: 's4',
      number: 4,
      title: 'บวกข้ามสิบ',
      intro: 'ด่าน 4 · บวกข้ามสิบ — คิดในใจแล้วตอบ',
      instruction: 'คิดในใจ แล้วตอบ',
      level: { good: { minCorrect: 4, minFluent: 3, maxCounting: 1 }, mid: { minCorrect: 3 } },
      items: stage4Items,
    },
    {
      id: 's5',
      number: 5,
      title: 'เลขสองหลัก',
      intro: 'ด่าน 5 · เลขสองหลัก — ด่านสุดท้าย! ใช้วิธีไหนก็ได้',
      instruction: 'คิดในใจ แล้วตอบ',
      skipIf: { stageId: 's4', correctAtMost: 1 },
      groups: [
        { id: '5A', itemIds: ['5.1', '5.2'], forbidStrategies: [] },
        { id: '5B', itemIds: ['5.3'], forbidStrategies: ['count-by-one'] },
        { id: '5C', itemIds: ['5.4'], forbidStrategies: ['count-by-one'] },
      ],
      items: stage5Items,
    },
  ],
  recommendation: [
    {
      no: 1,
      when: { kind: 'stage-not-good', stageId: 's1' },
      ladderStep: 1,
      reason:
        'ลูกยังต้องนับจุดทีละจุด ยังไม่เห็นก้อน 5 และ 10 ทันที ซึ่งเป็นฐานของทุกอย่างที่เหลือ',
    },
    {
      no: 2,
      when: { kind: 'stage-not-good', stageId: 's2' },
      ladderStep: 2,
      reason:
        'ลูกเห็นภาพ 10 ช่องได้แล้ว แต่คู่รวม 10 ยังไม่อัตโนมัติ ต้องแน่นก่อนถึงจะทำให้ครบ 10 ได้',
    },
    {
      no: 3,
      when: { kind: 'stage-not-good', stageId: 's3' },
      ladderStep: 3,
      reason:
        'คู่รวม 10 ได้แล้ว ต่อไปคือเลขคู่ ซึ่งเป็นทางลัดที่ใช้บ่อย ขั้นนี้ใช้เวลาไม่นาน แล้วไปขั้น 4 ต่อ',
    },
    {
      no: 4,
      when: { kind: 'stage-not-good', stageId: 's4' },
      ladderStep: 4,
      reason: 'พื้นฐานพร้อมแล้ว แต่บวกข้ามสิบยังนับต่ออยู่ ขั้นนี้สำคัญที่สุดของบันได',
    },
    {
      no: 5,
      when: { kind: 'group-not-pass', groupId: '5A', orStageSkipped: 's5' },
      ladderStep: 5,
      reason: 'บวกหลักเดียวคล่องแล้ว ขั้นต่อไปคือมองสิบเป็นก้อนหนึ่ง',
    },
    {
      no: 6,
      when: { kind: 'group-not-pass', groupId: '5B' },
      ladderStep: 6,
      reason: 'บวกสิบได้แล้ว ต่อไปคือแยกหลักสิบกับหน่วย',
    },
    {
      no: 7,
      when: { kind: 'group-not-pass', groupId: '5C' },
      ladderStep: 7,
      reason: 'แยกหลักได้แล้ว ต่อไปคือกระโดดบนเส้นจำนวน แล้วต่อด้วยการปัดให้กลม',
    },
    {
      no: 8,
      when: { kind: 'item-strategy-not', itemId: '5.4', strategyId: 'round' },
      ladderStep: 8,
      reason: 'พื้นฐานแน่นแล้ว ไปฝึกปัดให้กลมแล้วชดเชย เพื่อให้มีหลายวิธีให้เลือก',
    },
    {
      no: 9,
      when: { kind: 'always' },
      ladderStep: 9,
      reason: 'ลูกมีหลายวิธีแล้ว ไปฝึกเลือกวิธีเองและอธิบายว่าทำไม',
    },
  ],
  texts: {
    parentIntro: {
      title: 'ภารกิจสำรวจการบวก',
      description:
        '20 ข้อ ใช้เวลาประมาณ 7–10 นาที ผลลัพธ์จะบอกว่าควรเริ่มฝึกที่ขั้นไหนของบันไดการบวก',
      bullets: [
        { strong: 'ให้ลูกทำเอง', text: ' คุณพ่อนั่งดูข้างๆ ได้ แต่ไม่ต้องใบ้' },
        { strong: 'ไม่ต้องห้ามนับนิ้ว', text: ' เราอยากเห็นวิธีที่ลูกใช้จริง' },
        {
          strong: 'ระบบจับเวลาแบบเงียบๆ',
          text: ' ลูกจะไม่เห็นตัวจับเวลาและจะไม่รู้ว่าข้อไหนถูกหรือผิดระหว่างทำ เพื่อไม่ให้กดดัน',
        },
        { text: 'บางข้อจะถามว่า "หนูคิดยังไง" ถ้าลูกไม่แน่ใจ คุณพ่อช่วยเลือกจากที่เห็นได้' },
      ],
      button: 'ต่อไป: หน้าของลูก',
    },
    kidIntro: {
      title: 'ช่วยพ่อสำรวจหน่อย!',
      lines: [
        'อันนี้ไม่ใช่การสอบ ตอบผิดได้ ไม่เป็นไรเลย พ่ออยากรู้แค่ว่าหนูคิดยังไง',
        'มี 5 ด่าน ด่านแรกภาพจะโผล่มาแป๊บเดียว ต้องดูให้ไว!',
      ],
      button: 'เริ่มภารกิจ',
    },
    stageGo: 'ไปเลย',
    flash: { ready: 'พร้อมนะ...', show: 'ดู!', hidden: 'ซ่อนแล้ว! กี่จุดนะ?' },
    answerPlaceholder: 'แตะตัวเลขด้านล่าง',
    submit: 'ตอบ',
    acks: ['รับแล้ว!', 'โอเค ไปต่อ!', 'เยี่ยม ขอบคุณ!'],
    strategyQuestion: 'หนูคิดข้อนี้ยังไง?',
    stageComplete: 'ผ่านด่าน {n} แล้ว! เหลืออีก {m} ด่าน',
    kidEnd: {
      title: 'ภารกิจสำเร็จ!',
      text: 'ขอบคุณที่ช่วยพ่อสำรวจนะ ส่งเครื่องให้พ่อดูผลได้เลย',
      button: 'ให้พ่อดูผล',
    },
    results: {
      recommend: 'แนะนำให้เริ่มที่ ขั้นที่ {n}: {name}',
      parentNote:
        'ถ้าเห็นว่าผลไม่ตรงกับที่รู้จักลูก ให้เชื่อสิ่งที่เห็นและเลือกขั้นเองได้ ผลนี้มาจากโจทย์ 20 ข้อเท่านั้น',
      incomplete: 'ยังทำไม่ครบ ควรทำต่อให้จบก่อน',
      levels: { good: 'คล่องแล้ว', mid: 'ยังไม่อัตโนมัติ', low: 'ยังไม่แน่น', skipped: 'ข้าม' },
      ladderPassed: 'ผ่านแล้ว',
      ladderStart: '← เริ่มตรงนี้',
      noMisconception: 'ไม่พบรูปแบบความเข้าใจผิด',
      retry: 'ทำใหม่อีกครั้ง',
      stageStatusIncomplete: 'ทำไม่ครบ',
      stageStatusNotReached: 'ยังไม่ได้ทำ',
      groupPass: 'ผ่าน',
      groupFail: 'ยังไม่ผ่าน',
      groupSkipped: 'ข้าม',
      groupNotEvaluated: 'ยังไม่ได้ทำ',
      inProgressBadge: 'หยุดกลางทาง',
      fluentYes: 'ใช่',
      fluentNo: 'ไม่',
      fluentDash: '—',
      correct: 'ถูก',
      wrongWithExpected: 'ผิด · เฉลย {expected}',
      timeFootnote: '* สลับแอปหรือหยุดระหว่างข้อนี้ ไม่นำเวลามาคิด',
      foundInItems: 'พบในข้อ {itemIds}',
    },
    stop: {
      title: 'หยุดภารกิจนี้?',
      body: 'ผลจะประเมินจากด่านที่ทำครบเท่านั้น',
      confirmLabel: 'หยุดและดูผล',
      cancelLabel: 'ทำต่อ',
    },
  },
  numberTalks: {
    items: [
      {
        ladderStep: 1,
        prompt:
          'วางเหรียญหรือเลโก้ 7 ชิ้นในกล่องไข่ 10 ช่อง (หรือวาดตาราง 2×5) ให้ดู 2 วินาทีแล้วปิด',
        questions: ['เห็นกี่อัน', 'รู้ได้ยังไงโดยไม่ต้องนับ'],
      },
      {
        ladderStep: 2,
        prompt: '7 กับอะไรได้ 10',
        questions: ['รู้ได้ยังไง', 'ถ้าเป็น 6 ล่ะ ต่างกันยังไง'],
      },
      {
        ladderStep: 3,
        prompt: '7 + 8',
        questions: ['หนูคิดยังไง', 'มีเลขคู่ซ่อนอยู่ไหม'],
      },
      {
        ladderStep: 4,
        prompt: '8 + 5',
        questions: ['หนูคิดยังไง', 'ถ้าต้องทำให้ 8 เป็น 10 ก่อน จะทำยังไง'],
      },
      {
        ladderStep: 5,
        prompt: '47 + 10',
        questions: ['สิบที่เพิ่มมาไปอยู่ตรงไหน'],
      },
      {
        ladderStep: 6,
        prompt: '38 + 25',
        questions: ['หนูคิดยังไง', 'มีวิธีอื่นไหม'],
      },
      {
        ladderStep: 7,
        prompt: '38 + 25',
        questions: ['ถ้ากระโดดบนเส้นจำนวน จะกระโดดยังไง'],
      },
      {
        ladderStep: 8,
        prompt: '49 + 26',
        questions: ['49 ใกล้เลขอะไรที่บวกง่าย'],
      },
      {
        ladderStep: 9,
        prompt: '99 + 47',
        questions: ['วิธีไหนเร็วที่สุด ทำไม'],
      },
    ],
    rules: [
      'ถามวิธีคิดก่อน อย่าเพิ่งบอกว่าถูกหรือผิด',
      'ถ้าลูกนับ ไม่ต้องห้าม ถามว่า "มีวิธีที่เร็วกว่านี้ไหม"',
      'วาดสิ่งที่ลูกเล่าเป็นภาพ (เช่น number bond) ให้ลูกเห็น',
      'ไม่พูดว่า "ง่ายนิดเดียว" หรือ "เก่งมาก" ให้ชมที่วิธีคิด เช่น "วิธีนี้ฉลาดดี เพราะ..."',
    ],
  },
};
